config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'artworks#index'

  resources :departments
  resources :classifications
  resources :artworks
  resources :artists

  namespace :suggests do
    get :artists
    get :artworks
    get :classifications
    get :departments
    get :all_models
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord
  include Multisearch
  include PgSuggest

  validates :display_name, presence: true
  validates :constituent_id, presence: true, uniqueness: true

  has_many :artworks, foreign_key: :constituent_id, primary_key: :constituent_id

  # For PgSearchDocs
  alias_attribute :title, :display_name
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @pagy, @artists = pagy(Artist.all)
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_artist
    @artist = Artist.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def artist_params
    # params.fetch(:artist, {})
    params.require(:artist).permit(
      %i[
        constituent_id
        display_name
        artist_bio
        nationality
        gender
        begin_date
        end_date
        wiki
        qid
        ulan
      ]
    )
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artists</h1>

<artists-suggester></artists-suggester>

<table class="table">
  <thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Nationality</th>
    <th scope="col">Years</th>
    <th scope="col">Gender</th>
  </tr>
  </thead>

  <tbody>
  <% @artists.each do |artist| %>
    <tr>
      <td><%= link_to artist.title, artist %></td>
      <td><%= artist.nationality %></td>
      <td><%= artist.begin_date %> - <%= artist.end_date %></td>
      <td><%= artist.gender %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%== pagy_nav_bootstrap @pagy %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @artist.title %></h1>
<h4>Nationality: <%= @artist.nationality %></h4>
<h4>Gender: <%= @artist.gender %></h4>
<h4>Years: <%= @artist.begin_date %> -  <%= @artist.end_date %></h4>

<h5>Bio:</h5>
<p><%= @artist.artist_bio %></p>
<p>Wiki: <%= @artist.wiki %></p>
<p>ULAN:<%= @artist.ulan %> </p>


<%= link_to 'All artists', artists_path %>