config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'artworks#index'

  resources :departments
  resources :classifications
  resources :artworks
  resources :artists

  namespace :suggests do
    get :artists
    get :artworks
    get :classifications
    get :departments
    get :all_models
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  include Filterable
  include Multisearch
  include PgSuggest

  validates :title, presence: true

  belongs_to :artist, foreign_key: :constituent_id, primary_key: :constituent_id
  belongs_to :classification, optional: true
  belongs_to :department, optional: true

  # Filters
  scope :artwork, ->(ids_string) { where(id: ids_string.to_array)}
  scope :artist, ->(ids_string) { where(constituent_id: Artist.where(id: ids_string.to_array).pluck(:constituent_id))}
  scope :classification, ->(ids_string) { where(classification_id: ids_string.to_array)}
  scope :department, ->(ids_string) { where(department_id: ids_string.to_array)}
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: [:show, :edit, :update, :destroy]

  # GET /artworks
  # GET /artworks.json
  def index
    @pagy, @artworks = pagy(Artwork.filter(filtering_params).order(:thumbnail_url))
  end

  # GET /artworks/1
  # GET /artworks/1.json
  def show
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
  end

  # POST /artworks
  # POST /artworks.json
  def create
    @artwork = Artwork.new(artwork_params)

    respond_to do |format|
      if @artwork.save
        format.html { redirect_to @artwork, notice: 'Artwork was successfully created.' }
        format.json { render :show, status: :created, location: @artwork }
      else
        format.html { render :new }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artworks/1
  # PATCH/PUT /artworks/1.json
  def update
    respond_to do |format|
      if @artwork.update(artwork_params)
        format.html { redirect_to @artwork, notice: 'Artwork was successfully updated.' }
        format.json { render :show, status: :ok, location: @artwork }
      else
        format.html { render :edit }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1
  # DELETE /artworks/1.json
  def destroy
    @artwork.destroy
    respond_to do |format|
      format.html { redirect_to artworks_url, notice: 'Artwork was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_artwork
    @artwork = Artwork.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def artwork_params
    params.require(:artwork).permit(
      %i[
        constituent_id
        classification_id
        department_id
        title
        date
        medium
        dimensions
        credit_line
        accession_number
        date_acquired
        cataloged
        url
        thumbnail_url
        circumference
        depth
        diameter
        height
        length
        weight
        width
        seat_height
        duration
      ]
    )
  end

  def filtering_params
    params.permit(
      filter: [
        :artist,
        :artwork,
        :classification,
        :department
              ]
    )
  end

end

app/helpers/artworks_helper.rb
module ArtworksHelper
  def thumbnail(thumbnail_url, options={})
    url = thumbnail_url || "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="
    "<img class='img-thumbnail mr-4' src='#{url}' alt='#{options[:alt]}'>".html_safe
  end
end

app/views/artworks/_form.html.erb
<%= form_with(model: artwork, local: true) do |form| %>
  <% if artwork.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
      <% artwork.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artworks/edit.html.erb
<h1>Editing Artwork</h1>

<%= render 'form', artwork: @artwork %>

<%= link_to 'Show', @artwork %> |
<%= link_to 'Back', artworks_path %>

app/views/artworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artworks</h1>

<h5>Demo of suggester for singe model - Artwork</h5>
<artworks-suggester></artworks-suggester>

<h5>Demo of suggester for multi models - Artwork, Artists, Classifications, Departments</h5>
<p>Will suggest matches in all models. Fill filter Artworks by selectiong model - as example filter all artwork of Author </p>

<multi-suggester></multi-suggester>

<ul class="list-unstyled">
  <% @artworks.each do |artwork| %>
    <li class="media">
      <%= link_to thumbnail(artwork.thumbnail_url), artwork %>
      <div class="media-body">
        <h5 class="mt-0 mb-1"><%= link_to artwork.title, artwork %></h5>
        <h6>Accession Number: <%= artwork.accession_number %></h6>
        <h6>Artist: <%= link_to artwork.artist.title, artwork.artist %></h6>
        <h6>Department: <%= link_to artwork.department.title, artwork.department %></h6>
        <h6>Classification: <%= link_to artwork.classification.title, artwork.classification %></h6>
      </div>
    </li>
  <% end %>

</ul>


<%== pagy_nav_compact_bootstrap @pagy %>

app/views/artworks/new.html.erb
<h1>New Artwork</h1>

<%= render 'form', artwork: @artwork %>

<%= link_to 'Back', artworks_path %>

app/views/artworks/show.html.erb
<p id="notice"><%= notice %></p>



<h1><%= @artwork.title %></h1>
<%= thumbnail(@artwork.thumbnail_url) %>

<p><strong>Date </strong>:  <%= @artwork.date %> </p>
<p><strong>Medium </strong>:  <%= @artwork.medium %> </p>
<p><strong>Dimensions </strong>:  <%= @artwork.dimensions %> </p>
<p><strong>Credit_line </strong>:  <%= @artwork.credit_line %> </p>
<p><strong>Accession_number </strong>:  <%= @artwork.accession_number %> </p>
<p><strong>Date_acquired </strong>:  <%= @artwork.date_acquired %> </p>
<p><strong>Cataloged </strong>:  <%= @artwork.cataloged %> </p>
<p><strong>Url </strong>: <a href="<%= @artwork.url %>" target="_blank"><%= @artwork.url %></a> </p>
<p><strong>Thumbnail_url </strong>:  <%= @artwork.thumbnail_url %> </p>
<p><strong>Circumference </strong>:  <%= @artwork.circumference %> </p>
<p><strong>Depth </strong>:  <%= @artwork.depth %> </p>
<p><strong>Diameter </strong>:  <%= @artwork.diameter %> </p>
<p><strong>Height </strong>:  <%= @artwork.height %> </p>
<p><strong>Length </strong>:  <%= @artwork.length %> </p>
<p><strong>Weight </strong>:  <%= @artwork.weight %> </p>
<p><strong>Width </strong>:  <%= @artwork.width %> </p>
<p><strong>Seat_height </strong>:  <%= @artwork.seat_height %> </p>
<p><strong>Duration </strong>:  <%= @artwork.duration %> </p>

<%= link_to 'Back', artworks_path %>