config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'artworks#index'

  resources :departments
  resources :classifications
  resources :artworks
  resources :artists

  namespace :suggests do
    get :artists
    get :artworks
    get :classifications
    get :departments
    get :all_models
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/classification.rb
class Classification < ApplicationRecord
  include Multisearch
  include PgSuggest

  validates :title, presence: true

  has_many :artworks
end

app/controllers/classifications_controller.rb
class ClassificationsController < ApplicationController
  before_action :set_classification, only: [:show, :edit, :update, :destroy]

  # GET /classifications
  # GET /classifications.json
  def index
    @pagy, @classifications = pagy(Classification.all)
  end

  # GET /classifications/1
  # GET /classifications/1.json
  def show
  end

  # GET /classifications/new
  def new
    @classification = Classification.new
  end

  # GET /classifications/1/edit
  def edit
  end

  # POST /classifications
  # POST /classifications.json
  def create
    @classification = Classification.new(classification_params)

    respond_to do |format|
      if @classification.save
        format.html { redirect_to @classification, notice: 'Classification was successfully created.' }
        format.json { render :show, status: :created, location: @classification }
      else
        format.html { render :new }
        format.json { render json: @classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classifications/1
  # PATCH/PUT /classifications/1.json
  def update
    respond_to do |format|
      if @classification.update(classification_params)
        format.html { redirect_to @classification, notice: 'Classification was successfully updated.' }
        format.json { render :show, status: :ok, location: @classification }
      else
        format.html { render :edit }
        format.json { render json: @classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classifications/1
  # DELETE /classifications/1.json
  def destroy
    @classification.destroy
    respond_to do |format|
      format.html { redirect_to classifications_url, notice: 'Classification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classification
      @classification = Classification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classification_params
      params.require(:classification).permit(:title)
    end
end

app/helpers/classifications_helper.rb
module ClassificationsHelper
end

app/views/classifications/_form.html.erb
<%= form_with(model: classification, local: true) do |form| %>
  <% if classification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(classification.errors.count, "error") %> prohibited this classification from being saved:</h2>

      <ul>
      <% classification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/classifications/edit.html.erb
<h1>Editing Classification</h1>

<%= render 'form', classification: @classification %>

<%= link_to 'Show', @classification %> |
<%= link_to 'Back', classifications_path %>

app/views/classifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Classifications</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classifications.each do |classification| %>
      <tr>
        <td><%= classification.title %></td>
        <td><%= link_to 'Show', classification %></td>
        <td><%= link_to 'Edit', edit_classification_path(classification) %></td>
        <td><%= link_to 'Destroy', classification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%== pagy_nav_bootstrap @pagy %>

app/views/classifications/new.html.erb
<h1>New Classification</h1>

<%= render 'form', classification: @classification %>

<%= link_to 'Back', classifications_path %>

app/views/classifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @classification.title %>
</p>

<%= link_to 'Edit', edit_classification_path(@classification) %> |
<%= link_to 'Back', classifications_path %>